add_library(OpenAL STATIC)
target_folder(OpenAL ${FOLDER_EXTERNAL})

target_sources(OpenAL PRIVATE
  common/alcomplex.cpp
  common/alfstream.cpp
  common/almalloc.cpp
  common/alstring.cpp
  common/dynload.cpp
  common/polyphase_resampler.cpp
  common/ringbuffer.cpp
  common/strutils.cpp
  common/threads.cpp
  al/auxeffectslot.cpp
  al/buffer.cpp
  al/effect.cpp
  al/effects/autowah.cpp
  al/effects/chorus.cpp
  al/effects/compressor.cpp
  al/effects/convolution.cpp
  al/effects/dedicated.cpp
  al/effects/distortion.cpp
  al/effects/echo.cpp
  al/effects/effects.cpp
  al/effects/equalizer.cpp
  al/effects/fshifter.cpp
  al/effects/modulator.cpp
  al/effects/null.cpp
  al/effects/pshifter.cpp
  al/effects/reverb.cpp
  al/effects/vmorpher.cpp
  al/error.cpp
  al/event.cpp
  al/extension.cpp
  al/filter.cpp
  al/listener.cpp
  al/source.cpp
  al/state.cpp
  al/eax/api.cpp
  al/eax/call.cpp
  al/eax/exception.cpp
  al/eax/fx_slot_index.cpp
  al/eax/fx_slots.cpp
  al/eax/globals.cpp
  al/eax/utils.cpp
  alc/alc.cpp
  alc/alu.cpp
  alc/alconfig.cpp
  alc/context.cpp
  alc/device.cpp
  alc/effects/autowah.cpp
  alc/effects/chorus.cpp
  alc/effects/compressor.cpp
  alc/effects/convolution.cpp
  alc/effects/dedicated.cpp
  alc/effects/distortion.cpp
  alc/effects/echo.cpp
  alc/effects/equalizer.cpp
  alc/effects/fshifter.cpp
  alc/effects/modulator.cpp
  alc/effects/null.cpp
  alc/effects/pshifter.cpp
  alc/effects/reverb.cpp
  alc/effects/vmorpher.cpp
  alc/panning.cpp
  alc/backends/base.cpp
  alc/backends/loopback.cpp
  alc/backends/null.cpp
  alc/backends/winmm.cpp
  alc/backends/dsound.cpp
  alc/backends/wasapi.cpp
  alc/backends/wave.cpp
  core/ambdec.cpp
  core/ambidefs.cpp
  core/bformatdec.cpp
  core/bs2b.cpp
  core/bsinc_tables.cpp
  core/buffer_storage.cpp
  core/context.cpp
  core/converter.cpp
  core/cpu_caps.cpp
  core/cubic_tables.cpp
  core/devformat.cpp
  core/device.cpp
  core/effectslot.cpp
  core/except.cpp
  core/filters/biquad.cpp
  core/filters/nfc.cpp
  core/filters/splitter.cpp
  core/fmt_traits.cpp
  core/fpu_ctrl.cpp
  core/helpers.cpp
  core/hrtf.cpp
  core/logging.cpp
  core/mastering.cpp
  core/mixer.cpp
  core/uhjfilter.cpp
  core/uiddefs.cpp
  core/voice.cpp
  core/mixer/mixer_c.cpp
  core/mixer/mixer_sse.cpp
  core/mixer/mixer_sse2.cpp
  core/mixer/mixer_sse3.cpp
  core/mixer/mixer_sse41.cpp

  common/albit.h
  common/albyte.h
  common/alcomplex.h
  common/aldeque.h
  common/alfstream.h
  common/almalloc.h
  common/alnumbers.h
  common/alnumeric.h
  common/aloptional.h
  common/alspan.h
  common/alstring.h
  common/altraits.h
  common/atomic.h
  common/comptr.h
  common/dynload.h
  common/intrusive_ptr.h
  common/opthelpers.h
  common/phase_shifter.h
  common/polyphase_resampler.h
  common/pragmadefs.h
  common/ringbuffer.h
  common/strutils.h
  common/threads.h
  common/vecmat.h
  common/vector.h
  al/auxeffectslot.h
  al/buffer.h
  al/effect.h
  al/effects/effects.h
  al/event.h
  al/filter.h
  al/listener.h
  al/source.h
  al/eax/api.h
  al/eax/call.h
  al/eax/effect.h
  al/eax/exception.h
  al/eax/fx_slot_index.h
  al/eax/fx_slots.h
  al/eax/globals.h
  al/eax/utils.h
  al/eax/x_ram.h
  alc/alu.h
  alc/alconfig.h
  alc/context.h
  alc/device.h
  alc/effects/base.h
  alc/inprogext.h
  alc/backends/base.h
  alc/backends/loopback.h
  alc/backends/null.h
  alc/backends/winmm.h
  alc/backends/dsound.h
  alc/backends/wasapi.h
  alc/backends/wave.h
  core/ambdec.h
  core/ambidefs.h
  core/async_event.h
  core/bformatdec.h
  core/bs2b.h
  core/bsinc_defs.h
  core/bsinc_tables.h
  core/bufferline.h
  core/buffer_storage.h
  core/context.h
  core/converter.h
  core/cpu_caps.h
  core/cubic_defs.h
  core/cubic_tables.h
  core/devformat.h
  core/device.h
  core/effects/base.h
  core/effectslot.h
  core/except.h
  core/filters/biquad.h
  core/filters/nfc.h
  core/filters/splitter.h
  core/fmt_traits.h
  core/fpu_ctrl.h
  core/front_stablizer.h
  core/helpers.h
  core/hrtf.h
  core/logging.h
  core/mastering.h
  core/mixer.h
  core/resampler_limits.h
  core/uhjfilter.h
  core/voice.h
  core/voice_change.h
  core/mixer/defs.h
  core/mixer/hrtfbase.h
  core/mixer/hrtfdefs.h
)

target_include_directories(OpenAL
  PUBLIC
  ${CMAKE_CURRENT_SOURCE_DIR}/include
  PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}
  ${CMAKE_CURRENT_SOURCE_DIR}/common
)

target_compile_options(OpenAL
  PRIVATE
  $<$<CXX_COMPILER_ID:MSVC>:/wd4244>
  $<$<CXX_COMPILER_ID:MSVC>:/WX->
)

target_compile_definitions(OpenAL
  PUBLIC
  AL_LIBTYPE_STATIC
  PRIVATE
  AL_BUILD_LIBRARY
  AL_ALEXT_PROTOTYPES
  ALC_API=
  AL_API=
  _WIN32
  NOMINMAX
  RESTRICT=__restrict
  _CRT_SECURE_NO_WARNINGS
)

set_target_properties(OpenAL PROPERTIES
  CXX_STANDARD 17
)

target_link_libraries(OpenAL
  PRIVATE
  winmm
  ole32
)
