add_module(XRay.Core.Memory.Manager
  SOURCES
  memory_allocation_stats.cpp
  memory_usage.cpp
  xrMemory.cpp
  xrMemory_align.cpp
  xrMemory_debug.cpp
  xrMemory_POOL.cpp
  xrMemory_pso_Copy.cpp
  xrMemory_pso_Fill.cpp
  xrMemory_pso_Fill32.cpp
  xrMemory_subst_msvc.cpp
  
  xrMemory.h
  xrMemory_align.h
  xrMEMORY_POOL.h
  xrMemory_pso.h
  xrMemory_pure.h
  xrMemory_subst_msvc.h
)
