add_module(XRay.Render.Common
  INCLUDES
  ${CMAKE_CURRENT_SOURCE_DIR}
  ${XRAY_SOURCES}/Include/xrRender

  DEFINES
  R_R1=1
  R_R2=2
  R_R3=3
  R_R4=4

  SOURCES
  #blenders/Blender.cpp
  blenders/Blender.h
  blenders/Blender_CLSID.h
  ##blenders/Blender_Palette.cpp
  #blenders/Blender_Recorder.cpp
  blenders/Blender_Recorder.h

  #Debug/dxPixEventWrapper.cpp
  Debug/dxPixEventWrapper.h

  #Utils/dxHashHelper.cpp
  Utils/dxHashHelper.h
  #Animation.cpp
  Animation.h
  AnimationKeyCalculate.h
  #Blender_BmmD.cpp
  Blender_BmmD.h
  #Blender_detail_still.cpp
  Blender_detail_still.h
  #Blender_Editor_Selection.cpp
  Blender_Editor_Selection.h
  #Blender_Editor_Wire.cpp
  Blender_Editor_Wire.h
  #"Blender_Lm(EbB).cpp"
  "Blender_Lm(EbB).h"
  #Blender_Model_EbB.cpp
  Blender_Model_EbB.h
  #Blender_Particle.cpp
  Blender_Particle.h
  #Blender_Recorder_R2.cpp
  #Blender_Recorder_StandartBinding.cpp
  #Blender_Screen_SET.cpp
  Blender_Screen_SET.h
  #Blender_tree.cpp
  Blender_tree.h
  cl_intersect.h
  CMakeLists.txt
  #ColorMapManager.cpp
  ColorMapManager.h
  #D3DUtils.cpp
  D3DUtils.h
  DetailFormat.h
  #DetailManager.cpp
  DetailManager.h
  #DetailManager_CACHE.cpp
  #DetailManager_Decompress.cpp
  #DetailManager_soft.cpp
  #DetailManager_VS.cpp
  #DetailModel.cpp
  DetailModel.h
  #doug_lea_memory_allocator.c
  #du_box.cpp
  du_box.h
  #du_cone.cpp
  du_cone.h
  #du_cylinder.cpp
  du_cylinder.h
  #du_sphere.cpp
  du_sphere.h
  #du_sphere_part.cpp
  du_sphere_part.h
  #dxApplicationRender.cpp
  dxApplicationRender.h
  #dxConsoleRender.cpp
  dxConsoleRender.h
  #dxDebugRender.cpp
  dxDebugRender.h
  #dxEnvironmentRender.cpp
  dxEnvironmentRender.h
  #dxFontRender.cpp
  dxFontRender.h
  #dxImGuiRender.cpp
  dxImGuiRender.h
  #dxLensFlareRender.cpp
  dxLensFlareRender.h
  #dxObjectSpaceRender.cpp
  dxObjectSpaceRender.h
  #dxParticleCustom.cpp
  dxParticleCustom.h
  #dxRainRender.cpp
  dxRainRender.h
  #dxRenderDeviceRender.cpp
  dxRenderDeviceRender.h
  #dxRenderFactory.cpp
  dxRenderFactory.h
  #dxStatGraphRender.cpp
  dxStatGraphRender.h
  #dxStatsRender.cpp
  dxStatsRender.h
  #dxThunderboltDescRender.cpp
  dxThunderboltDescRender.h
  #dxThunderboltRender.cpp
  dxThunderboltRender.h
  #dxUIRender.cpp
  dxUIRender.h
  #dxUISequenceVideoItem.cpp
  dxUISequenceVideoItem.h
  #dxUIShader.cpp
  dxUIShader.h
  #dxWallMarkArray.cpp
  dxWallMarkArray.h
  #ETextureParams.cpp
  ETextureParams.h
  #Example_of_ok_renderphase.cpp
  #FBasicVisual.cpp
  FBasicVisual.h
  #FHierrarhyVisual.cpp
  FHierrarhyVisual.h
  #FLOD.cpp
  FLOD.h
  #FProgressive.cpp
  FProgressive.h
  #FSkinned.cpp
  FSkinned.h
  #FTreeVisual.cpp
  FTreeVisual.h
  FVF.h
  #FVisual.cpp
  FVisual.h
  #HOM.cpp
  HOM.h
  #HW.cpp
  HW.h
  #HWCaps.cpp
  HWCaps.h
  IRenderDetailModel.h
  KinematicAnimatedDefs.h
  #light.cpp
  light.h
  #Light_DB.cpp
  Light_DB.h
  #Light_Package.cpp
  Light_Package.h
  #LightTrack.cpp
  LightTrack.h
  #ModelPool.cpp
  ModelPool.h
  #NvTriStrip.cpp
  NvTriStrip.h
  #NvTriStripObjects.cpp
  NvTriStripObjects.h
  #occRasterizer.cpp
  occRasterizer.h
  #occRasterizer_core.cpp
  #ParticleEffect.cpp
  ParticleEffect.h
  #ParticleEffectActions.cpp
  ParticleEffectActions.h
  #ParticleEffectDef.cpp
  ParticleEffectDef.h
  #ParticleGroup.cpp
  ParticleGroup.h
  #PSLibrary.cpp
  PSLibrary.h
  QueryHelper.h
  #r__dsgraph_build.cpp
  #r__dsgraph_render.cpp
  #r__dsgraph_render_lods.cpp
  r__dsgraph_structure.h
  r__dsgraph_types.h
  #r__occlusion.cpp
  r__occlusion.h
  #r__pixel_calculator.cpp
  r__pixel_calculator.h
  #r__screenshot.cpp
  #r__sector.cpp
  r__sector.h
  #r__sector_traversal.cpp
  #R_Backend.cpp
  R_Backend.h
  #R_Backend_DBG.cpp
  #R_Backend_hemi.cpp
  R_Backend_hemi.h
  #R_Backend_Runtime.cpp
  R_Backend_Runtime.h
  #R_Backend_tree.cpp
  R_Backend_tree.h
  #R_Backend_xform.cpp
  R_Backend_xform.h
  #r_constants.cpp
  r_constants.h
  r_constants_cache.h
  #R_DStreams.cpp
  R_DStreams.h
  r_sun_cascades.h
  #rendertarget_phase_blur.cpp
  #rendertarget_phase_dof.cpp
  #rendertarget_phase_gasmask_drops.cpp
  #rendertarget_phase_gasmask_dudv.cpp
  #rendertarget_phase_lut.cpp
  #rendertarget_phase_nightvision.cpp
  #rendertarget_phase_pp_bloom.cpp
  #rendertarget_phase_smaa.cpp
  #rendertarget_phase_sunshafts.cpp
  light.h
  #ResourceManager.cpp
  ResourceManager.h
  #ResourceManager_Loader.cpp
  #ResourceManager_Reset.cpp
  #ResourceManager_Resources.cpp
  #ResourceManager_Scripting.cpp
  #SH_Atomic.cpp
  SH_Atomic.h
  #SH_Constant.cpp
  SH_Constant.h
  #SH_Matrix.cpp
  SH_Matrix.h
  #SH_RT.cpp
  SH_RT.h
  #SH_Texture.cpp
  SH_Texture.h
  #Shader.cpp
  Shader.h
  ShaderResourceTraits.h
  #SkeletonAnimated.cpp
  SkeletonAnimated.h
  #SkeletonCustom.cpp
  SkeletonCustom.h
  #SkeletonRigid.cpp
  #SkeletonX.cpp
  SkeletonX.h
  SkeletonXVertRender.h
  #stats_manager.cpp
  stats_manager.h
  #Texture.cpp
  #TextureDescrManager.cpp
  TextureDescrManager.h
  #tga.cpp
  tga.h
  tss.h
  #tss_def.cpp
  tss_def.h
  #uber_deffer.cpp
  uber_deffer.h
  #VertexCache.cpp
  VertexCache.h
  #WallmarksEngine.cpp
  WallmarksEngine.h
  #xr_effgamma.cpp
  xr_effgamma.h
  xrD3DDefs.h
  #xrRender_console.cpp
  xrRender_console.h
  #xrStripify.cpp
  xrStripify.h
)
