add_module(XRay.Game.AI.Cover
  SOURCES
  cover_point_script.cpp
  cover_point.h
  cover_point_inline.h

  smart_cover.cpp
  smart_cover_action.cpp
  smart_cover_animation_planner.cpp
  smart_cover_animation_selector.cpp
  smart_cover_default_behaviour_planner.cpp
  smart_cover_description.cpp
  smart_cover_detail.cpp
  smart_cover_evaluators.cpp
  smart_cover_loophole.cpp
  smart_cover_loophole_planner_actions.cpp
  smart_cover_object.cpp
  smart_cover_object_script.cpp
  smart_cover_planner_actions.cpp
  smart_cover_planner_target_provider.cpp
  smart_cover_planner_target_selector.cpp
  smart_cover_storage.cpp
  smart_cover_transition.cpp
  smart_cover_transition_animation.cpp

  smart_cover.h
  smart_cover_action.h
  smart_cover_action_inline.h
  smart_cover_animation_planner.h
  smart_cover_animation_planner_inline.h
  smart_cover_animation_selector.h
  smart_cover_animation_selector_inline.h
  smart_cover_default_behaviour_planner.hpp
  smart_cover_default_behaviour_planner_inline.hpp
  smart_cover_description.h
  smart_cover_description_inline.h
  smart_cover_detail.h
  smart_cover_evaluators.h
  smart_cover_inline.h
  smart_cover_loophole.h
  smart_cover_loophole_inline.h
  smart_cover_loophole_planner_actions.h
  smart_cover_loophole_planner_actions_inline.h
  smart_cover_object.h
  smart_cover_object_inline.h
  smart_cover_planner_actions.h
  smart_cover_planner_actions_inline.h
  smart_cover_planner_target_provider.h
  smart_cover_planner_target_selector.h
  smart_cover_planner_target_selector_inline.h
  smart_cover_storage.h
  smart_cover_transition.hpp
  smart_cover_transition_animation.hpp
  smart_cover_transition_animation_inline.hpp

  cover_manager.cpp
  cover_manager.h
  cover_manager_inline.h
)
