add_cmake_directory(XRay)

add_subdirectory("3rd party")

add_subdirectory("Layers")

add_subdirectory("xrCDB")
add_subdirectory("xrCore")
add_subdirectory("xrCPU_Pipe")
add_subdirectory("xrEngine")
add_subdirectory("xrGame")
add_subdirectory("xrNetServer")
add_subdirectory("xrParticles")
add_subdirectory("xrPhysics")
add_subdirectory("xrServerEntities")
add_subdirectory("xrSound")
add_subdirectory("xrXMLParser")
add_subdirectory("ReShadeCompat")
