include_guard()

# Setup and enforce language standards
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)

set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED True)

message(STATUS "        C++${CMAKE_CXX_STANDARD}: ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "          C${CMAKE_C_STANDARD}: ${CMAKE_C_COMPILER_ID}")

# Setup global compiler definitions
include(XRay.Compiler.Definitions)

# Configure toolchain-specific settings
if(CMAKE_CXX_COMPILER_ID MATCHES MSVC)
  include(XRay.Compiler.MSVC)
elseif(CMAKE_CXX_COMPILER_ID MATCHES Clang)
  include(XRay.Compiler.Clang)
elseif(CMAKE_CXX_COMPILER_ID MATCHES GNU)
  include(XRay.Compiler.GNU)
else()
  include(XRay.Compiler.Unsupported)
endif()

# Normalize existing compiler flags
if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
  string(REPLACE "/EHsc" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
  string(REPLACE "/EHsc" "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
  string(REPLACE "/Zi" "" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
  string(REPLACE "/Zi" "" CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}")
  string(REPLACE "/Ob2" "" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
  string(REPLACE "/Ob2" "" CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
  string(REPLACE "/Ob1" "" CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
  string(REPLACE "/Ob1" "" CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO}")
else()
  string(REPLACE "-O0 -g" "" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
  string(REPLACE "-O0 -g" "" CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}")
  string(REPLACE "-O3" "" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
  string(REPLACE "-O3" "" CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
  string(REPLACE "-O2" "" CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
  string(REPLACE "-O2" "" CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO}")
endif()

# Append X-Ray compiler flags
string(JOIN " " CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} ${XRAY_COMPILER_FLAGS})
string(JOIN " " CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG} ${XRAY_COMPILER_FLAGS_DEBUG})
string(JOIN " " CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE} ${XRAY_COMPILER_FLAGS_RELEASE})
string(JOIN " " CMAKE_CXX_FLAGS_RELWITHDEBINFO ${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${XRAY_COMPILER_FLAGS_RELEASE})

string(JOIN " " CMAKE_C_FLAGS ${CMAKE_C_FLAGS} ${XRAY_COMPILER_FLAGS})
string(JOIN " " CMAKE_C_FLAGS_DEBUG ${CMAKE_C_FLAGS_DEBUG} ${XRAY_COMPILER_FLAGS_DEBUG})
string(JOIN " " CMAKE_C_FLAGS_RELEASE ${CMAKE_C_FLAGS_RELEASE} ${XRAY_COMPILER_FLAGS_RELEASE})
string(JOIN " " CMAKE_C_FLAGS_RELWITHDEBINFO ${CMAKE_C_FLAGS_RELWITHDEBINFO} ${XRAY_COMPILER_FLAGS_RELEASE})

# Setup Verified configuration
set(CMAKE_CXX_FLAGS_VERIFIED ${CMAKE_CXX_FLAGS_DEBUG})
set(CMAKE_C_FLAGS_VERIFIED ${CMAKE_C_FLAGS_DEBUG})

if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
  string(REPLACE "/EHsc" "" CMAKE_CXX_FLAGS_VERIFIED "${CMAKE_CXX_FLAGS_VERIFIED}")
  string(REPLACE "/EHsc" "" CMAKE_C_FLAGS_VERIFIED "${CMAKE_C_FLAGS_VERIFIED}")
  string(REPLACE "/RTC1" "" CMAKE_CXX_FLAGS_VERIFIED "${CMAKE_CXX_FLAGS_VERIFIED}")
  string(REPLACE "/RTC1" "" CMAKE_C_FLAGS_VERIFIED "${CMAKE_C_FLAGS_VERIFIED}")
endif()

if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
  set(CMAKE_CXX_FLAGS_VERIFIED "${CMAKE_CXX_FLAGS_VERIFIED} /DNDEBUG /DUSE_VERIFY_IN_RELEASE")
  set(CMAKE_C_FLAGS_VERIFIED "${CMAKE_C_FLAGS_VERIFIED} /DNDEBUG /DUSE_VERIFY_IN_RELEASE")
else()
  set(CMAKE_CXX_FLAGS_VERIFIED "${CMAKE_CXX_FLAGS_VERIFIED} -DNDEBUG -DUSE_VERIFY_IN_RELEASE")
  set(CMAKE_C_FLAGS_VERIFIED "${CMAKE_C_FLAGS_VERIFIED} -DNDEBUG -DUSE_VERIFY_IN_RELEASE")
endif()

# Setup Debug configuration
if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /DDEBUG")
else()
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DDEBUG")
endif()

# Setup Profiled configuration
set(CMAKE_CXX_FLAGS_PROFILED ${CMAKE_CXX_FLAGS_RELEASE})
set(CMAKE_C_FLAGS_PROFILED ${CMAKE_C_FLAGS_RELEASE})

string(REPLACE "/GL " "" CMAKE_CXX_FLAGS_PROFILED ${CMAKE_CXX_FLAGS_PROFILED})
string(REPLACE "/GL " "" CMAKE_C_FLAGS_PROFILED ${CMAKE_C_FLAGS_PROFILED})

# Match vcxproj Profiled: no aggressive inlining or function-level linking
string(REPLACE "/Ob3" "" CMAKE_CXX_FLAGS_PROFILED "${CMAKE_CXX_FLAGS_PROFILED}")
string(REPLACE "/Ob3" "" CMAKE_C_FLAGS_PROFILED "${CMAKE_C_FLAGS_PROFILED}")
string(REPLACE "/Gy" "" CMAKE_CXX_FLAGS_PROFILED "${CMAKE_CXX_FLAGS_PROFILED}")
string(REPLACE "/Gy" "" CMAKE_C_FLAGS_PROFILED "${CMAKE_C_FLAGS_PROFILED}")

if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
  set(CMAKE_CXX_FLAGS_PROFILED "${CMAKE_CXX_FLAGS_PROFILED} /DXRCORE_PROFILER=1")
  set(CMAKE_C_FLAGS_PROFILED "${CMAKE_C_FLAGS_PROFILED} /DXRCORE_PROFILER=1")
else()
  set(CMAKE_CXX_FLAGS_PROFILED "${CMAKE_CXX_FLAGS_PROFILED} -DXRCORE_PROFILER=1")
  set(CMAKE_C_FLAGS_PROFILED "${CMAKE_C_FLAGS_PROFILED} -DXRCORE_PROFILER=1")
endif()

set(MESSAGE_LEVEL DEBUG)

# Print compile flags
message(${MESSAGE_LEVEL})
message(${MESSAGE_LEVEL} "C++ Flags:")
message(${MESSAGE_LEVEL} "        Global: ${CMAKE_CXX_FLAGS}")
message(${MESSAGE_LEVEL} "         Debug: ${CMAKE_CXX_FLAGS_DEBUG}")
message(${MESSAGE_LEVEL} "      Verified: ${CMAKE_CXX_FLAGS_VERIFIED}")
message(${MESSAGE_LEVEL} "      Profiled: ${CMAKE_CXX_FLAGS_PROFILED}")
message(${MESSAGE_LEVEL} "       Release: ${CMAKE_CXX_FLAGS_RELEASE}")
message(${MESSAGE_LEVEL} "RelWithDebInfo: ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")

message(${MESSAGE_LEVEL})
message(${MESSAGE_LEVEL} "C Flags:")
message(${MESSAGE_LEVEL} "        Global: ${CMAKE_CXX_FLAGS}")
message(${MESSAGE_LEVEL} "         Debug: ${CMAKE_CXX_FLAGS_DEBUG}")
message(${MESSAGE_LEVEL} "      Verified: ${CMAKE_CXX_FLAGS_VERIFIED}")
message(${MESSAGE_LEVEL} "      Profiled: ${CMAKE_CXX_FLAGS_PROFILED}")
message(${MESSAGE_LEVEL} "       Release: ${CMAKE_CXX_FLAGS_RELEASE}")
message(${MESSAGE_LEVEL} "RelWithDebInfo: ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
