if(${XRAY_AVX})
  message(STATUS "          AVX: On")
  if(CMAKE_CXX_COMPILER_ID STREQUAL MSVC)
    add_compile_options(/arch:AVX)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL Clang)
    add_compile_options(-mavx)
  endif()
else()
  message(STATUS "          AVX: Off")
endif()
